configuration:
  server:
    port: 8761
  spring:
    name: registry
server:
  port: ${configuration.server.port}
spring:
  application:
    name: ${configuration.spring.name}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    com: 
      netflix:
        eureka: OFF
        discovery: OFF