configuration:
  server:
    port: 8111
  spring:
    name: api
server:
  port: ${configuration.server.port}
spring:
  application:
    name: ${configuration.spring.name}
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    name: test
    data: classpath:sql/data.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    format_sql: true
